### ISSUE TITLE
Adding PerisanQA : a dataset for Persian Question Answering

### ISSUE THREAD

**Issue by sajjjadayobi** [Mofid-AI/persian-nlp-benchmark#1]
[PersianQA](https://github.com/sajjjadayobi/PersianQA)  is a reading comprehension dataset on Persian Wikipedia. The crowd-sourced dataset consists of more than 9,000 entries, We train a baseline model which achieves an F1 score of 78 and an exact match ratio of 52 on [ParsiNLU](https://github.com/persiannlp/parsinlu).

I will be more than happy to work with you on adding this dataset (+ model) if you encounter any difficulties

**Comment by zfallahnejad** [comment]
You are very welcome to contribute to our repository by sending a pull request.
Follow these steps to add a dataset for the task of reading comprehension:
1. See [reading_comprehension.py](reading_comprehension.py) for this task. Update `load_dataset_test_file` method of `ReadingComprehension` class, so it can be used to load your dataset.
2. There is a notebook for each model in this [path](notebooks/reading-comprehension). Update ReadingComprehension class of these notebooks based on step 1, and create an instance of this class. Then, add a section for your dataset. Fill out this section of the notebook, just as we did for the Parsinlu dataset. First, download the dataset and load the test section with the help of `load_dataset_test_file` method, print the hardware specifications, and evaluate the model.
3. Update readme file. Provide a brief description of the dataset in the section related to this task. Prepare a table for your dataset (similar to the existing one) and fill it with the evaluation results.
4. Finally, please send us a pull request. 

Follow these steps to add a model for the task of reading comprehension:
1. See [reading_comprehension.py](reading_comprehension.py) for this task. Consider adding an inference method for testing multiple input samples (similar to existing methods) if necessary. Include an evaluation method if necessary so that the input dataset can be evaluated by the model.
2. Create a notebook for this model in this [path](notebooks/reading-comprehension). The name of this notebook should be a combination of the task name and the model name.  Please fill in the content of this notebook exactly like the existing notebooks. Don't forget to put the updated code of the ReadingComprehension class in the notebook if you update it in step 1. Create a section for each dataset and evaluate the model.
3. Include the evaluation results in the relevant tables of the readme file.
4. Send us a pull request. 

We would appreciate it if you could follow these steps to ensure a unified format for the benchmark. Please feel free to contact [me](z.fallahnejad@gmail.com) if you have any questions.
